name: Run Pytest on Push

on: push  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v4

    # Étape 2 : Installer Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # Étape 3 : Installer pytest uniquement
    - name: Install pytest
      run: pip install pytest

    # Étape 4 : Lancer les tests
    - name: Run tests with pytest
      run: pytest -v
